# Generated by Django 5.1.4 on 2024-12-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='usuario',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='contiene',
            unique_together={('reserva', 'producto')},
        ),
    ]
