# Generated by Django 5.1.4 on 2024-12-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0002_remove_metodopago_usuario_metodopago_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='pais',
            field=models.CharField(default='Argentina', max_length=50),
        ),
        migrations.AddField(
            model_name='tienda',
            name='provincia',
            field=models.CharField(default='Buenos Aires', max_length=50),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='categoria',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('supermercado', 'Supermercado'), ('ropa', 'Ropa'), ('tecnologia', 'Tecnología'), ('belleza', 'Belleza'), ('deportes', 'Deportes'), ('veterinaria', 'Veterinaria'), ('salud', 'Salud'), ('autopartes', 'Autopartes'), ('construccion y ferreteria', 'Construccion y ferreteria'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
