# Generated by Django 5.1.4 on 2024-12-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0003_tienda_pais_tienda_provincia_alter_tienda_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='coordenada_latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='coordenada_longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
