# Generated by Django 5.1.4 on 2024-12-23 15:47

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0006_alter_tienda_dias_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='categoria',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('restaurante', 'Restaurante'), ('supermercado', 'Supermercado'), ('ropa', 'Ropa'), ('tecnologia', 'Tecnología'), ('belleza', 'Belleza'), ('deportes', 'Deportes'), ('veterinaria', 'Veterinaria'), ('salud', 'Salud'), ('autopartes', 'Autopartes'), ('construccion_y_ferreteria', 'Construcción y Ferretería'), ('otros', 'Otros')], default=['otros'], max_length=118),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='dias_atencion',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('lunes_a_viernes', 'Lunes a Viernes'), ('lunes_a_sabado', 'Lunes a Sábado'), ('todos_los_dias', 'Todos los días')], default=['lunes_a_viernes'], max_length=98),
        ),
    ]
