# Generated by Django 5.1.4 on 2024-12-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0007_alter_tienda_categoria_alter_tienda_dias_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='categoria',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('supermercado', 'Supermercado'), ('ropa', 'Ropa'), ('tecnologia', 'Tecnología'), ('belleza', 'Belleza'), ('deportes', 'Deportes'), ('veterinaria', 'Veterinaria'), ('salud', 'Salud'), ('autopartes', 'Autopartes'), ('construccion_y_ferreteria', 'Construcción y Ferretería'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='dias_atencion',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('lunes_a_viernes', 'Lunes a Viernes'), ('lunes_a_sabado', 'Lunes a Sábado'), ('todos_los_dias', 'Todos los días')], default='lunes_a_viernes', max_length=50),
        ),
    ]
