# Generated by Django 5.1.4 on 2024-12-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0009_alter_tienda_categoria_alter_tienda_dias_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='categoria',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('supermercado', 'Supermercado'), ('ropa', 'Ropa'), ('tecnologia', 'Tecnologia'), ('belleza', 'Belleza'), ('deportes', 'Deportes'), ('veterinaria', 'Veterinaria'), ('salud', 'Salud'), ('autopartes', 'Autopartes'), ('construccion_y_ferreteria', 'Construccion y Ferreteria'), ('polirrubro', 'Polirrubro'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
