# Generated by Django 5.1.4 on 2024-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0010_alter_tienda_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='provincia',
            field=models.CharField(max_length=50),
        ),
    ]
