# Generated by Django 5.1.4 on 2024-12-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0011_alter_tienda_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='provincia',
            field=models.CharField(default='Buenos Aires', max_length=50),
        ),
    ]
