# Generated by Django 5.1.4 on 2024-12-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0012_alter_tienda_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia_bancaria', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('qr', 'Código QR'), ('monedero_electronico', 'Monedero Electrónico'), ('criptomoneda', 'Criptomoneda'), ('pasarela_en_linea', 'Pasarela de Pago en Línea'), ('cheque', 'Cheque'), ('pagos_a_plazos', 'Pagos a Plazos'), ('vales', 'Vales/Tarjetas de Regalo'), ('contra_entrega', 'Pago contra Entrega'), ('debito_directo', 'Débito Directo'), ('creditos_internos', 'Créditos Internos/Monedas Virtuales')], default='efectivo', max_length=50),
        ),
    ]
