# Generated by Django 5.1.4 on 2024-12-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0014_remove_metodopago_tienda_alter_metodopago_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='metodos_pago',
            field=models.ManyToManyField(blank=True, to='Negocio.metodopago'),
        ),
    ]
