# Generated by Django 5.1.4 on 2024-12-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0015_tienda_metodos_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
