# Generated by Django 5.1.4 on 2025-01-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0016_remove_metodopago_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='provincia',
            field=models.CharField(default='Buenos Aires', max_length=50),
        ),
    ]
