# Generated by Django 5.1.4 on 2025-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0017_profile_provincia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_actual',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
