# Generated by Django 5.1.4 on 2025-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0018_rename_precio_actual_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_servicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
