# Generated by Django 5.1.4 on 2025-01-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0019_producto_es_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ReservaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_reservas', to='Negocio.producto')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_productos', to='Negocio.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='productos',
            field=models.ManyToManyField(related_name='reservas_producto', through='Negocio.ReservaProducto', to='Negocio.producto'),
        ),
    ]
