# Generated by Django 5.1.4 on 2025-01-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0021_producto_permite_reservas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp incluyendo código de país', max_length=20, null=True),
        ),
    ]
