# Generated by Django 5.1.4 on 2025-01-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0023_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('retirado', 'Retirado'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
