# Generated by Django 5.1.4 on 2025-01-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0026_alter_tienda_dias_atencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telefono',
        ),
    ]
