# Generated by Django 5.1.4 on 2025-01-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0027_remove_profile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='promocion_descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='promocion_unidad_descuento',
            field=models.IntegerField(blank=True, help_text='Aplicar descuento en la N-ésima unidad.', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='promocion_unidades',
            field=models.CharField(blank=True, help_text='Formato _x_ como 2x1, 3x2, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='permite_reservas',
            field=models.BooleanField(default=True),
        ),
    ]
