# Generated by Django 5.1.4 on 2025-01-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0029_remove_producto_promocion_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='promocion_nx',
            field=models.CharField(blank=True, help_text="Formato: 'NxM' (ejemplo: '2x1', '3x2')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='promocion_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento para la unidad específica', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='promocion_unidad',
            field=models.IntegerField(blank=True, choices=[(1, 'primera'), (2, 'segunda'), (3, 'tercera'), (4, 'cuarta'), (5, 'quinta'), (6, 'sexta'), (7, 'séptima'), (8, 'octava'), (9, 'novena'), (10, 'décima')], help_text='Unidad a la que se aplica el descuento porcentual', null=True),
        ),
    ]
