# Generated by Django 5.1.4 on 2025-01-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0030_producto_promocion_nx_producto_promocion_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url_logo',
            field=models.URLField(blank=True, help_text='URL del logo de la tienda en Imgur', null=True),
        ),
    ]
