# Generated by Django 5.1.4 on 2025-01-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0031_producto_url_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='url_logo',
        ),
        migrations.AddField(
            model_name='tienda',
            name='url_logo',
            field=models.URLField(blank=True, help_text='URL del logo de la tienda en Imgur', null=True),
        ),
    ]
