# Generated by Django 5.1.4 on 2025-01-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0032_remove_producto_url_logo_tienda_url_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='metodos_pago',
        ),
        migrations.RemoveField(
            model_name='detallereserva',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='tienda',
            name='cheque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='contra_entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='creditos_internos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='criptomoneda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='debito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='debito_directo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='efectivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='monedero_electronico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='pago_movil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='pagos_a_plazos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='pasarela_en_linea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='qr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='transferencia_bancaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='vales',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
    ]
