# Generated by Django 5.1.4 on 2025-01-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0033_remove_tienda_metodos_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='pais',
        ),
    ]
